name:                proxmox-deploy-toolkit
version:             0.1.2.0
github:              "learnew2/proxmox-deploy-toolkit"
license:             GPL-3.0-or-later
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2025 Ilya Zamaratskikh"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/learnew2/proxmox-deploy-toolkit#readme>

dependencies:
- base >= 4.7 && < 5
- servant == 0.19.1
- text == 2.0.2
- aeson == 2.1.2.1
- http-client == 0.7.14
- servant-client == 0.19
- http-conduit == 2.3.8.1
- connection == 0.3.1
- containers == 0.6.7
- transformers == 0.5.6.2
- mtl == 2.2.2
- http-types == 0.12.3
- monad-logger == 0.3.40
- bytestring == 0.11.5.2
- case-insensitive == 1.2.1.0
- scientific == 0.3.7.0
- yaml == 0.11.11.2
- exceptions == 0.10.5
- proxmox-api
- proxmox-fs-agent-api

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Proxmox.Deploy.Ssl
    - Proxmox.Deploy.Transaction
    - Proxmox.Deploy.Types
    - Proxmox.Deploy.VM
    - Proxmox.Deploy.Models.Config
    - Proxmox.Deploy.Models.Transaction
    - Proxmox.Deploy.Models.Config.VM
    - Proxmox.Deploy.Models.Config.Template
    - Proxmox.Deploy.Models.Config.Network
    - Proxmox.Deploy.Models.Config.Deploy
    - Proxmox.Deploy.Models.Config.DeployAgent
